### ISSUE TITLE
Wager commands should work on spam channel

### ISSUE THREAD

**Issue by joaofbmaia** [PedroMMFHenriques/jeraptha_v2#5]
The serious channel should be excluvisve only for the wager start command 🤔

**Comment by PedroMMFHenriques** [comment]
To do that some of the wager commands would have to be in a different commandGroup and so would appear as separate in the /help command. Alternatively, it would be necessary to hardcode the channel_id. So I recommend just enabling all the /wager commands on both channels and reprimand who uses the more spammy ones in the serious channel.

**Comment by PedroMMFHenriques** [comment]
.
